# Generated by Django 6.0.2 on 2026-02-04 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name of the AI agent', max_length=100)),
                ('category', models.CharField(choices=[('medical', 'Medical'), ('nutrition', 'Nutrition'), ('finance', 'Finance'), ('legal', 'Legal'), ('research', 'Research'), ('interview', 'Interview'), ('general', 'General')], help_text='Domain category of the agent', max_length=20)),
                ('system_prompt', models.TextField(help_text='System prompt defining agent behavior')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who created this agent', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
